# Exercícios da biblioteca Numpy

In [2]:
import numpy as np

## Problema 1
Uma planta industrial precisa monitorar os pHs de um processo de fermentação alcoólica da cana de açúcar, dentro de um reator, a cada 5 segundos. A começar pelo tempo 0, o monitoramento gera uma lista com 100 valores em segundos. Para auxiliar ao operador do reator e, também, para padronizar a aquisição dos valores de pH, uma matriz quadrada é disponibilizada para consulta, contendo os tempos em que é feito um registro de pH. Represente a matriz, bem como seu número de dimensões.

In [3]:
a = np.arange(0,5*100,5).reshape(10,-1)
print('A matriz é:')
print(a)
print('O número de dimensões das matrizes é:', a.ndim)

A matriz é:
[[  0   5  10  15  20  25  30  35  40  45]
 [ 50  55  60  65  70  75  80  85  90  95]
 [100 105 110 115 120 125 130 135 140 145]
 [150 155 160 165 170 175 180 185 190 195]
 [200 205 210 215 220 225 230 235 240 245]
 [250 255 260 265 270 275 280 285 290 295]
 [300 305 310 315 320 325 330 335 340 345]
 [350 355 360 365 370 375 380 385 390 395]
 [400 405 410 415 420 425 430 435 440 445]
 [450 455 460 465 470 475 480 485 490 495]]
O número de dimensões das matrizes é: 2


## Problema 2
Considerando a mesma matriz da questão anterior, suponha que haja dificuldade na leitura da matriz contendo os valores em segundos dispostos em linhas e que, para contornar o problema, foi definido que se adotaria a matriz com os tempos dispostos em colunas. Represente a matriz.

Além disso, supondo que agora será necessário apenas a leitura de pHs com intervalo de 10 segundos entre si, começando em 0 segundos, qual será a matriz resultante? Qual será o número de elementos nela?

In [4]:
a_transposta = a.transpose(1,0)
print('A transposta é:')
print(a_transposta, '\n')

b = np.delete(a_transposta, [1,3,5,7,9], 0)
print('A matriz, adotando o intervalo de 10 segundos, será:')
print (b)
print('Seu número de elementos será:', b.size)

A transposta é:
[[  0  50 100 150 200 250 300 350 400 450]
 [  5  55 105 155 205 255 305 355 405 455]
 [ 10  60 110 160 210 260 310 360 410 460]
 [ 15  65 115 165 215 265 315 365 415 465]
 [ 20  70 120 170 220 270 320 370 420 470]
 [ 25  75 125 175 225 275 325 375 425 475]
 [ 30  80 130 180 230 280 330 380 430 480]
 [ 35  85 135 185 235 285 335 385 435 485]
 [ 40  90 140 190 240 290 340 390 440 490]
 [ 45  95 145 195 245 295 345 395 445 495]] 

A matriz, adotando o intervalo de 10 segundos, será:
[[  0  50 100 150 200 250 300 350 400 450]
 [ 10  60 110 160 210 260 310 360 410 460]
 [ 20  70 120 170 220 270 320 370 420 470]
 [ 30  80 130 180 230 280 330 380 430 480]
 [ 40  90 140 190 240 290 340 390 440 490]]
Seu número de elementos será: 50


## Problema 3
Um processo muito importante, com aplicações variadas, como calcular integrais de linha sob campos vetoriais ou até definir bases ortonormais de subespaços vetoriais, é a normalização de um vetor. Assim, um vetor no R<sup>32</sup>, com entradas que variam crescentemente, com termo constante de soma igual a 2, começando de 6, precisa ser normalizado para resultar no vetor $x$. Apresente $x$.

In [8]:
# O vetor está em R^32, logo, tem 32 entradas. Estas seguem uma PA, com uma soma constante de 2 unidades, começando em 6.
# Assim, o último termo da PA segue a lógica de 6 + (32 - 1)*2.
vetor = np.arange(6, 6 + 32*2,2)
# Foi usado 6 + 32*2 pois o último termo, resultado dessa expressão, não é incluído pelo arange. O intervalo é aberto no último ponto.

norma = np.linalg.norm(vetor)

vetor_normalizado = vetor/norma

vetor_normalizado

array([0.02564946, 0.03419928, 0.0427491 , 0.05129892, 0.05984874,
       0.06839856, 0.07694838, 0.0854982 , 0.09404802, 0.10259784,
       0.11114765, 0.11969747, 0.12824729, 0.13679711, 0.14534693,
       0.15389675, 0.16244657, 0.17099639, 0.17954621, 0.18809603,
       0.19664585, 0.20519567, 0.21374549, 0.22229531, 0.23084513,
       0.23939495, 0.24794477, 0.25649459, 0.26504441, 0.27359423,
       0.28214405, 0.29069387])

## Problema 4 (desafio)
Numa placa de térmica, é possível determinar a temperatura do interior conhecendo-se apenas a temperatura nas bordas dela. Essa modelagem é feita da seguinte maneira: a temperatura em um ponto central da placa é igual à média aritmética dos pontos ao seu redor (isto é, à esquerda, à direnta, acima e abaixo). Sabendo isto, calcule os valores, em graus Celsius, de $x$, $y$, $z$ e $w$.

!['Calor'](https://i.pinimg.com/originals/96/f2/00/96f2000e77cb42dde7f9181af0925d5f.jpg)

#### Sugestão de resolução:
- Identifique o sistema linear referente à resolução do problema.
- Organize este sistema linear em uma matriz, utilizando as funções Numpy necessárias.
- Crie um algoritmo de escalonamento (total ou parcial, à sua escolha) para a resolução do sistema linear - é encorajada a manipulação do código presente na lista corrigida.
- Se for muito difícil, é possível usar a função "solve" do módulo linalg.

In [6]:
def escalonamento (A, b):

   M = np.concatenate( (A, b), axis=1 )
   M = M.astype(float)

   M = M[np.sum(abs(M),1)!=0,:]

   p,n = A.shape

   ### Parte I (forma escalonada)
   k = 0
   while k < p-1:
  
      c = np.argmax(np.sum(abs(M[k:,:]),0)!=0)
 
      if M[k,c]==0:

         r = (k+1)+np.argmax(M[(k+1):,c]!=0)

         M[[k,r],:] = M[[r,k],:]

      for r in range(k+1,p):
         M[r,c+1:] = M[r,c+1:] - (M[r,c]/M[k,c]) * M[k,c+1:]
         M[r,c] = 0

      M=M[np.sum(abs(M),1)!=0,:]

      p = M.shape[0]

      k = k + 1
   
   ### Parte II (forma totalmente escalonada)
   for k in range (p-1,-1,-1):

      c = np.argmax(M[k,:]!=0)

      M[k,c+1:] = M[k,c+1:] / M[k,c]
      M[k,c] = 1

      for r in range(0,k):
         M[r,c+1:] = M[r,c+1:] - M[r,c]*M[k,c+1:]
         M[r,c] = 0

   E = M[:,0:n]
   x = M[:,n:n+1]
   return E, x 

In [7]:
A = np.array([
    [4,-1,-1,0],
    [-1,4,0,-1],
    [-1,0,4,-1],
    [0,-1,-1,4]
])
b = np.array([
    [3],
    [-22],
    [14],
    [5]
])

E,x = escalonamento(A,b)

print (E,'\n')
print (x, '\n')

print ('O valor de x é de', round(float(x[0]),2), '°C')
print ('O valor de y é de', round(float(x[1]),2), '°C')
print ('O valor de z é de', round(float(x[2]),2), '°C')
print ('O valor de w é de', round(float(x[3]),2), '°C')

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[ 0.41666667]
 [-5.16666667]
 [ 3.83333333]
 [ 0.91666667]] 

O valor de x é de 0.42 °C
O valor de y é de -5.17 °C
O valor de z é de 3.83 °C
O valor de w é de 0.92 °C
